# -*- coding: utf-8 -*-
"""reto 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TjfBSe48m-fFwIKUmfv6-xupmnts1u0r
"""



"""Dado un numero determinar si tal numero corresponde al codigo ascii de una vocal minuscula"""

A : int
A = int(input("Ingrese un numero ENTERO: "))
A = chr(A)
if A == "a" or A == "e" or A == "i" or A == "o" or A == "u":
    print("El numero corresponde al codigo ascii de una vocal minuscula")
else:
  print("El numero no corresponde al codigo ascii de una vocal minuscula")

"""Dada una cadena de longitud 1, determine si el código ASCII de primera letra de la cadena es par o no.

"""

S : str
S = input("Ingrese una cadena de longitud 1: ")
S = ord(S)
if S % 2 == 0:
    print("El codigo ASCII de la primera letra es par")
else:
    print("El codigo ASCII de la primera letra es impar")

"""Dado un carácter, construya un programa en Python para determinar si el carácter es un dígito o no."""

b : str
b = input("Ingrese un caracter: ")
if b.isdigit():
    print("El caracter es un digito")
else:
    print("El caracter no es un digito")

"""Realice un programa que lea dos números reales y determine si el primero es múltiplo del segundo.

"""

a : int
b : int
a = input("Ingrese el primer numero entero: ")
b = input("Ingrese el segundo numero entero: ")
a = int(a)
b = int(b)
if a % b == 0:

    print("El primer numero es multiplo del segundo")
else:
    print("El primer numero no es multiplo del segundo")

"""Dado un número real x, construya un programa que permita determinar si el número es positivo, negativo o cero. Para cada caso de debe imprimir el texto que se especifica a continuación:"""

x = float
x = input("Ingrese un numero real: ")
x = float(x)
if x > 0:
    print("El numero es positivo")
elif x < 0:
    print("El numero es negativo")
else:
    print("El numero es cero")

"""Dado el centro y el radio de un círculo, determinar si un punto en el plano bidimensional pertenece o no al interior del círculo."""

x=input("ingrese la coordenada x del centro del circulo: ")
xc=float(xc)
yc=input("ingrese la coordenada y del centro del circulo: ")
yc=float(yc)
r=input("ingrese el radio del circulo: ")
r=float(r)
xp=input("ingrese la coordenada x del punto: ")
xp=float(xp)
yp=input("ingrese la coordenada y del punto: ")
yp=float(yp)
if (xp-xc)**2+(yp-yc)**2<=r**2:
    print("el punto pertenece al interior del circulo")
else:
    print("el punto no pertenece al interior del circulo")

Dadas tres longitudes positivas, determinar si con esas longitudes se puede construir un triángulo.

a=input("ingrese la longitud del primer lado: ")
a=float(a)
b=input("ingrese la longitud del segundo lado: ")
b=float(b)
c=input("ingrese la longitud del tercer lado: ")
c=float(c)
if a+b>c and a+c>b and b+c>a:
    print("se puede construir un triangulo")
else:
    print("no se puede construir un triangulo")

"""Escriba un programa que reciba el nombre en minúsculas de un país de America y retorne la ciudad capital, si el país no pertenece al continente debe arrojar país no identificado (Utilice match-case)."""

a = input("pone el nombre de un pais de america en minusculas: ")

match a:
    case "mexico":
        print("la capital es ciudad de mexico")
    case "bahamas":
        print("la capital es nasau")
    case "canada":
        print("la capital es ottawa")
    case "uruguay":
        print("la capital es montevideo")
    case "nicaragua":
        print("la capital es managua")
    case "costa rica":
        print("la capital es san jose")
    case "brasil":
        print("la capital es brasilia")
    case "dominica":
        print("la capital es roseau")
    case "el salvador":
        print("la capital es san salvador")
    case "panama":
        print("la capital es ciudad de panama")
    case "haiti":
        print("la capital es puerto principe")
    case "argentina":
        print("la capital es buenos aires")
    case "guatemala":
        print("la capital es ciudad de guatemala")
    case "peru":
        print("la capital es lima")
    case "colombia":
        print("la capital es bogota")
    case "granada":
        print("la capital es saint george")
    case "honduras":
        print("la capital es tegucigalpa")
    case "antigua y barbuda":
        print("la capital es saint john's")
    case "chile":
        print("la capital es santiago")
    case "trinidad y tobago":
        print("la capital es puerto españa")
    case "ecuador":
        print("la capital es quito")
    case "paraguay":
        print("la capital es asuncion")
    case "barbados":
        print("la capital es bridgetown")
    case "republica dominicana":
        print("la capital es santo domingo")
    case "bolivia":
        print("la capital es sucre y la paz")
    case "cuba":
        print("la capital es la habana")
    case "san cristobal y nieves":
        print("la capital es basseterre")
    case "san vicente y las granadinas":
        print("la capital es kingstown")
    case "san lucia":
        print("la capital es castries")
    case "jamaica":
        print("la capital es kingston")
    case "surinam":
        print("la capital es paramaribo")
    case "guyana":
        print("la capital es georgetown")
    case "belice":
        print("la capital es belmopan")
    case "estados unidos":
        print("la capital es washington d.c.")
    case "santa lucia":
        print("la capital es castries")
    case _:
        print("no se cual es ese pais o capaz esta mal escrito")